#############################################################################
# Makefile for building: airscan
# Generated by qmake (2.01a) (Qt 4.6.2) on: Sun Jul 11 19:53:09 2010
# Project:  airscan.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile airscan.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lm -lpcap -lssl -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = sniffer.c \
		xmalloc.c \
		qt.cpp \
		main.cpp \
		qt_sniff.cpp \
		qt_menu.cpp \
		qt_table.cpp \
		qt_progress_dialog.cpp \
		qt_crack.cpp \
		qt_th_iface.cpp \
		radiotap-parser.c \
		crypt/crypto.c moc_qt_menu.cpp \
		moc_qt_progress_dialog.cpp \
		moc_qt_th_iface.cpp
OBJECTS       = sniffer.o \
		xmalloc.o \
		qt.o \
		main.o \
		qt_sniff.o \
		qt_menu.o \
		qt_table.o \
		qt_progress_dialog.o \
		qt_crack.o \
		qt_th_iface.o \
		radiotap-parser.o \
		crypto.o \
		moc_qt_menu.o \
		moc_qt_progress_dialog.o \
		moc_qt_th_iface.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		airscan.pro
QMAKE_TARGET  = airscan
DESTDIR       = 
TARGET        = airscan

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: airscan.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile airscan.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile airscan.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/airscan1.0.0 || $(MKDIR) .tmp/airscan1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/airscan1.0.0/ && $(COPY_FILE) --parents qt_interface.h qt_menu.h sniffer.h common.h crypt/crypto.h qt_dialog.h qt_snif.h qt_common.h qt_table.h qt_progress_dialog.h qt_crack.h qt_th_iface.h qt.h .tmp/airscan1.0.0/ && $(COPY_FILE) --parents sniffer.c xmalloc.c qt.cpp main.cpp qt_sniff.cpp qt_menu.cpp qt_table.cpp qt_progress_dialog.cpp qt_crack.cpp qt_th_iface.cpp radiotap-parser.c crypt/crypto.c .tmp/airscan1.0.0/ && (cd `dirname .tmp/airscan1.0.0` && $(TAR) airscan1.0.0.tar airscan1.0.0 && $(COMPRESS) airscan1.0.0.tar) && $(MOVE) `dirname .tmp/airscan1.0.0`/airscan1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/airscan1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qt_menu.cpp moc_qt_progress_dialog.cpp moc_qt_th_iface.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qt_menu.cpp moc_qt_progress_dialog.cpp moc_qt_th_iface.cpp
moc_qt_menu.cpp: qt_dialog.h \
		qt_snif.h \
		qt_crack.h \
		sniffer.h \
		common.h \
		qt_table.h \
		qt_menu.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qt_menu.h -o moc_qt_menu.cpp

moc_qt_progress_dialog.cpp: qt_progress_dialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qt_progress_dialog.h -o moc_qt_progress_dialog.cpp

moc_qt_th_iface.cpp: qt_th_iface.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qt_th_iface.h -o moc_qt_th_iface.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

sniffer.o: sniffer.c sniffer.h \
		common.h \
		xmalloc.h \
		radiotap-parser.h \
		byteorder.h \
		ieee80211_radiotap.h \
		crypt/crypto.h \
		qt_interface.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sniffer.o sniffer.c

xmalloc.o: xmalloc.c common.h \
		sniffer.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o xmalloc.o xmalloc.c

qt.o: qt.cpp qt_interface.h \
		qt_menu.h \
		qt_dialog.h \
		qt_snif.h \
		qt_crack.h \
		sniffer.h \
		common.h \
		qt_table.h \
		qt_th_iface.h \
		qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qt.o qt.cpp

main.o: main.cpp sniffer.h \
		common.h \
		qt_interface.h \
		xmalloc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qt_sniff.o: qt_sniff.cpp qt_common.h \
		qt_snif.h \
		qt_crack.h \
		sniffer.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qt_sniff.o qt_sniff.cpp

qt_menu.o: qt_menu.cpp qt_menu.h \
		qt_dialog.h \
		qt_snif.h \
		qt_crack.h \
		sniffer.h \
		common.h \
		qt_table.h \
		qt_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qt_menu.o qt_menu.cpp

qt_table.o: qt_table.cpp qt_table.h \
		common.h \
		sniffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qt_table.o qt_table.cpp

qt_progress_dialog.o: qt_progress_dialog.cpp qt_progress_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qt_progress_dialog.o qt_progress_dialog.cpp

qt_crack.o: qt_crack.cpp qt_crack.h \
		sniffer.h \
		common.h \
		qt_interface.h \
		qt_common.h \
		xmalloc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qt_crack.o qt_crack.cpp

qt_th_iface.o: qt_th_iface.cpp qt_th_iface.h \
		qt_common.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qt_th_iface.o qt_th_iface.cpp

radiotap-parser.o: radiotap-parser.c radiotap-parser.h \
		byteorder.h \
		ieee80211_radiotap.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o radiotap-parser.o radiotap-parser.c

crypto.o: crypt/crypto.c crypt/crypto.h \
		crypt/crctable.h \
		crypt/aircrack-ng.h \
		crypt/aircrack-ptw-lib.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o crypto.o crypt/crypto.c

moc_qt_menu.o: moc_qt_menu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qt_menu.o moc_qt_menu.cpp

moc_qt_progress_dialog.o: moc_qt_progress_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qt_progress_dialog.o moc_qt_progress_dialog.cpp

moc_qt_th_iface.o: moc_qt_th_iface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qt_th_iface.o moc_qt_th_iface.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

